<article>
    <?php
        if(isset($_GET['request'])){
            switch($_GET['request']){
                case'trangchu':
                    include"views/trangchu.php";
                    break;
                case'tintuc':
                    include"views/tintuc.php";
                    break;
                case'tour':
                    include"views/tour.php";
                    break;
                case'gioithieu':
                    include"views/gioithieu.php";
                    break;
                case'dangnhap':
                    include"views/dnhap.php";
                    break;
                case'logout':
                    unset($_SESSION['user']);
                    header('location: .');
                    exit();
                    break;
                case'chitiettintuc':
                    include"views/chitiettintuc.php";
                    break;
                case'chitietsanpham':
                    include"views/chitietsanpham.php";
                    break;
                case'search':
                    include"lib/search.php";
                    break;           
                case'order':
                    include"views/order.php";
                    break;     
                case'giohang':
                    include"views/gio.php";
                    break; 
                case'canhan':
                    include"views/thongtinnguoidung.php";
                    break;   
                case'ttdangnhap':
                    include"views/thongtindangnhap.php";
                    break;   
                }            
            }else{
                include"views/trangchu.php";
            }
    ?>
</article>